---

- hosts: host
  remote_user: root

  vars:
  - golang_version: 1.6
  - golang_os: linux
  - golang_arch: amd64
  - gopath: /usr/go

  environment:
  - GOPATH: /usr/go

  tasks:
  - include: tasks/init.yml

  - include: tasks/skycoin.yml
  - include: tasks/mzcoin.yml
  - include: tasks/exchange.yml

  - name: Run the services
    shell: supervisord -c /etc/supervisord.conf
