---

- hosts: host_alpine
  remote_user: root

  vars:
  - golang_installation: /usr/local
  - binaries_dir: /usr/bin

  tasks:
  - name: Update packages
    shell: apk update
  - name: Get GNU tar
    shell: apk add tar

  - include: tasks/golang.yml


- hosts: host_debian
  remote_user: root

  vars:
  - golang_installation: /usr/local/src

  environment:
  - GOPATH: /usr/go

  tasks:
  - include: tasks/golang.yml
  - include: tasks/debian/init.yml

  - include: tasks/debian/skycoin.yml
  - include: tasks/debian/mzcoin.yml
  - include: tasks/debian/exchange.yml

  - name: Run the services
    shell: supervisord -c /etc/supervisord.conf

